### ISSUE TITLE
Special Session Open Source IO at IIOA 2023

### ISSUE THREAD

**Issue by konstantinstadler** [CIRAIG/OpenIO-Canada#15]
Hi folks,

Just a short question:
I check if there is enough interest for a special session on Open Source software for IO development/analysis at the IIOA 2023 (https://iioa.org/conferences/29th/important_dates.html ). Would any of the authors of OpenIO-Canada to be interested in presenting there?

Cheers
Konstantin

**Comment by MaximeAgez** [comment]
Hi Konstantin,
Thanks for the suggestion. I am personally interested in presenting. Nevertheless, I need to check with my colleagues. I'll get back to you soon.
Maxime

**Comment by MaximeAgez** [comment]
@konstantinstadler In the end we will go present to the Life Cycle Management (LCM) conference, so we won't be able to go to the IIOA. Sorry.
