### ISSUE TITLE
Use for independent project

### ISSUE THREAD

**Issue by gkcRoute** [CIRAIG/OpenIO-Canada#17]
Hi, 

I was wondering if this code would be able to allow me to calculate my Canadian company's scope 3 emissions by inputting all the units we have purchased from suppliers?

**Comment by MaximeAgez** [comment]
Hi,
Yes, it would. You just have to create a demand vector (let's call it v) in which you input whatever your company is purchasing. And then you do the following calculation: tables.C.dot(tables.S).dot(tables.L).dot(v).
That will provide you with the scope 2 and 3 of your company. Then you need to sort out things a bit to separate scope 2 from 3.

**Comment by gkcRoute** [comment]
Thank you for responding! 

Is there a specific template of the demand vector to input the values?

**Comment by MaximeAgez** [comment]
For the rows of the vector you can just copy the rows of the Y matrix. If you have multiple factories/products you could have a column for each and then input the corresponding purchases on the different rows.
