### ISSUE TITLE
if you please write the tables names as written in demo what are these tables it will help. Thanks

### ISSUE THREAD

**Issue by rehananis** [CIRAIG/OpenIO-Canada#19]
I was looking for 2019 IO table but it look like it is already normalized. if you kindly mention the name of these tables it could help me to understand the code. Thanks

        self.V = pd.DataFrame()
        self.U = pd.DataFrame()
        self.A = pd.DataFrame()  # technology matrix, covering 13 Canadian provinces, 44 country and 5 Rest of the World region
        self.K = pd.DataFrame()  # capital matrix (only available if you chose to endogenize capitals)
        self.Z = pd.DataFrame()
        self.W = pd.DataFrame()
        self.R = pd.DataFrame()  # normalized value added
        self.Y = pd.DataFrame()  # final demand
        self.WY = pd.DataFrame()
        self.g = pd.DataFrame()
        self.inv_g = pd.DataFrame()
        self.q = pd.DataFrame()
        self.inv_q = pd.DataFrame()
        self.F = pd.DataFrame()   # environmental flow matrix
        self.S = pd.DataFrame()  # normalized environmental flow matrix
        self.FY = pd.DataFrame()   # direct emissions from final demand
        self.C = pd.DataFrame()   # characterization matrix (using IW+)
        self.INT_imports = pd.DataFrame()
        self.L = pd.DataFrame()    # Leontief inverse
        self.E = pd.DataFrame()
        self.D = pd.DataFrame()  # total emissions per final demand sector
        self.who_uses_int_imports_U = pd.DataFrame()
        self.who_uses_int_imports_K = pd.DataFrame()
        self.who_uses_int_imports_Y = pd.DataFrame()
        self.A_exio = pd.DataFrame()
        self.K_exio = pd.DataFrame()
        self.S_exio = pd.DataFrame()
        self.F_exio = pd.DataFrame()
        self.C_exio = pd.DataFrame()
        self.link_openio_exio_A = pd.DataFrame()
        self.link_openio_exio_K = pd.DataFrame()
        self.link_openio_exio_Y = pd.DataFrame()
        self.merchandise_imports = pd.DataFrame()
        self.merchandise_imports_scaled_U = pd.DataFrame()
        self.merchandise_imports_scaled_K = pd.DataFrame()
        self.merchandise_imports_scaled_Y = pd.DataFrame()
        self.minerals = pd.DataFrame()

**Comment by MaximeAgez** [comment]
You identified the main ones that are used to make the calculations. The others are only necessary to construct the matrices you identified.
You can look at V (Supply matrix) and U (Use matrix) also. The rest does not really matter.
