### ISSUE TITLE
Inter-provincial trade emmisions

### ISSUE THREAD

**Issue by rehananis** [CIRAIG/OpenIO-Canada#23]
Hi, can I calculate inter-provincial trade emissions from OpenIO-Canada model?

**Comment by MaximeAgez** [comment]
Sure, though it is not provided by default so you will have to perform the calculation on your own. 
You need to isolate the parts of the final demand and intermediary demand that are imported from another province. You can achieve that by selecting specific index/columns with `.loc[]` and only taking the ones starting with 'CA-'.

**Comment by rehananis** [comment]
Hi Agez,
I need help with this high-level programming. I am lost; please guide me more on where I have to make changes first because I have noticed that you added provincial exports in self.U. 

line 380. Provincial exports will be included in self.U

**Comment by MaximeAgez** [comment]
In the A matrix you need to only account for inter-provincial trade, so put to zero anything that is not part of Canada and that is not the province you are looking at. Same with the K matrix, for inter-provincial trade of capital goods. Then recalculate the Leontief inverse L with the modified A and K matrices. Multiply L by S and C and you will get the impact of inter-provincial trade linked to imports from the industries.
Then, you need to modify the final demand matrix Y to only cover inter-provincial trade. Multiply the modified Y matrix by the typical L (so not with the modified A and K from before), S and C to get the inter-provincial trade impact of final demand imports.
