### ISSUE TITLE
Loading error when following the demo

### ISSUE THREAD

**Issue by hha-mm** [CIRAIG/OpenIO-Canada#24]
Following the demo (https://github.com/CIRAIG/OpenIO-Canada/blob/master/doc/demo.ipynb)

Getting the following error at the 'Endogenizing capitals' stage:
<img width="945" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/195c7f8a-49db-4110-b981-67175d29d336">

If I disable endogenizing capitals and run again, I get a similar error at the 'Balancing interprovincial trade' stage:
<img width="940" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/7fd87af2-bee3-43d7-ae3e-d263ad4cfe14">

I am using the recommended pandas version (1.3.4), so this is not a duplicate of #21.
Here is the full library version list:
<img width="211" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/1672a064-4af6-4895-b45e-319777b41e6f">
Using numpy 1.21.0 instead of 1.20.3, because it crashes with 1.20.3 (matplotlib requires >1.21.0).

This is with the 2019 datasets, copying the demo.

**Comment by MaximeAgez** [comment]
Hi!. Code seems to be running fine on numpy 1.21.0, so it must not be the root of the issue. I'll keep looking into it.

**Comment by hha-mm** [comment]
Hi! Thanks for looking into this. 

This was on Python 3.9.7:
<img width="663" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/89376991-f9b6-4308-b9d5-26e95367a074">

I've tested again with matplotlib on an older version (3.7.0) and numpy changed to the recommended version (1.20.3), still on Python 3.9.7:
<img width="194" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/2c866b19-d9e1-4646-afaf-6f3b592ac335">
And I get the same error as before:
<img width="843" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/96b5702d-bd1b-4631-ae8d-b94152714567">

By the way, matplotlib 3.8.3 does support Python 3.9.X:
<img width="363" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/1aa824bd-0397-4a70-b591-43a7eb734ba3">
(taken from: https://matplotlib.org/devdocs/devel/min_dep_policy.html)

**Comment by hha-mm** [comment]
Could it be an issue with the Statcan/Exiobase datasets?
I used the 2019 versions, copying the demo, but I have the same issue with the 2022 and 2020 versions.

Specifically, I used these files:
https://www150.statcan.gc.ca/n1/pub/15-602-x/15-602-x2017001-eng.htm
<img width="588" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/8595e1db-e3cd-4949-88db-3f91299b5c65">

and 
https://zenodo.org/records/5589597
<img width="556" alt="image" src="https://github.com/CIRAIG/OpenIO-Canada/assets/162201853/4ad9fbcd-5528-452c-954d-3b52d4db6af5">

**Comment by MaximeAgez** [comment]
These are the correct files.

Are you using the latest version of openIO-Canada?

**Comment by hha-mm** [comment]
> Are you using the latest version of openIO-Canada?
Yes, the latest commit.

**Comment by MaximeAgez** [comment]
Could you try with the 2.8 release? Maybe I broke something on some machines with the latest commit.
If it's still does not work with the 2.8 release we could have a call if you want to look into it live.

**Comment by hha-mm** [comment]
Just tried the 2.8 release; same issue. 
I'm up for a call. 236-317-9964

**Comment by hha-mm** [comment]
I think I found the cause of the issue.

Turns out it only works if you use forward slashes in the filepath for the folder_path param. I was using backslashed file-paths (system default on Windows using os.sep and os.path functions); switching to forward slashes fixed it.
See: https://github.com/CIRAIG/OpenIO-Canada/blob/master/openIO.py#L56

**Comment by MaximeAgez** [comment]
Perfect. Thanks for the modification :)
